name: agentic-rl-from-yaml
model:
  name: qwen3.5-9b
functions:
- type: rollout
  name: rollout-1
  timeout: 600
  fcmodel:
    zipdir: ./
    classpath: functions.rollout.rollout.CalcXRolloutProcessor
    requirements_path: ./requirements.txt
  runtime:
    cpu: 2.0
    memory_size: 4096
    disk_size: 512
    concurrency: 30
    capacity: 30
    max_capacity: 60
    min_capacity: 30
    memory_scale_threshold: 0.6
    concurrency_scale_threshold: 0.6
    env: {}
- type: reward
  name: rewards-1
  timeout: 120
  fcmodel:
    zipdir: ./
    classpath: functions.reward.reward.DemoRewardProcessor
    requirements_path: ./requirements.txt
  runtime:
    cpu: 2.0
    memory_size: 4096
    disk_size: 512
    concurrency: 30
    capacity: 30
    max_capacity: 60
    min_capacity: 30
    memory_scale_threshold: 0.6
    concurrency_scale_threshold: 0.6
    env: {}
  weight: 1.0
  reward_metric_weight:
    reward_metric_weightA: 0.3
    reward_metric_weightB: 0.7
datasets:
- type: training
  data_source_type: file_id
  file_name: ./data/calc_train_min.jsonl
- type: validation
  data_source_type: file_id
  file_name: ./data/calc_validation_min.jsonl
training:
  type: reinforcement
  hyper_parameters:
    algorithm: gspo
    batch_size: 64
    eval_steps: 1
    kl_loss_coef: 0.002
    learning_rate: 2e-6
    lr_scheduler_type: linear
    max_length: 8192
    n_epochs: 1
    n_rollouts: 8
    ppo_mini_batch_size: 8
    save_steps: 100
    save_strategy: steps
    save_total_limit: 1
  resources:
    charge_type: mtu_postpaid
    mtu_spec_code: MTU4
    mtu_capacity: 24
observability: {}
